import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <div className="container max-w-screen-xl mx-auto px-4 py-6 md:px-0">
            <nav className="flex items-center justify-between font-bold text-white">
              <a href="" className="flex items-center space-x-3 ">
                <img src="/logo1.svg" className="h-8" alt="Brisk EV Logo" />
                <img src="/logo2.svg" className="h-8" alt="Brisk EV Logo" />
              </a>

              <div className="hidden h-10 md:flex md:items-center space-x-8">
                <a href="">Home</a>
                <a href="">Product</a>
                <a href="">Find A Dealer</a>
                <a href="">Pricing</a>
                <button
                  type="button"
                  className="primary-button dark:text-white bg-blue-700  focus:ring-4 focus:ring-blue-300 font-medium rounded text-sm px-5 py-2.5  focus:outline-none dark:focus:ring-blue-800"
                >
                  Book Now
                </button>
              </div>
              <div className="md:hidden">
                <button
                  id="menu-btn"
                  type="button"
                  className="z-40 block hamburger md:hidden focus:outline-none"
                >
                  <span className="hamburger-top"></span>
                  <span className="hamburger-middle"></span>
                  <span className="hamburger-bottom"></span>
                </button>
              </div>
            </nav>
            <div
              id="menu"
              className="absolute top-0 left-0 hidden flex-col self-end w-full min-h-screen py-1 pt-40 pl-12 space-y-3 text-lg text-white uppercase bg-black"
            >
              <a href="#" className="hover:text-pink-500">
                About
              </a>
              <a href="#" className="hover:text-pink-500">
                Careers
              </a>
              <a href="#" className="hover:text-pink-500">
                Events
              </a>
              <a href="#" className="hover:text-pink-500">
                Products
              </a>
              <a href="#" className="hover:text-pink-500">
                Support
              </a>
            </div>
          </div>
        </header>
        <main>{children}</main>
        <footer className="bg-gray-100">
          <div className="container max-w-5xl mx-auto py-20 text-black">
            <div className="flex flex-col item-center space-y-6 md:flex-row md:space-y-0 md:justify-between md:items-start mb-5">
              <div className="flex flex-col items-center md:flex-row md:items-start space-y-4">
                <div className="h-8">
                  <img src="footer_logo.svg" alt="" className="w-44 md:ml-3" />
                </div>
              </div>

              <div className="flex flex-col items-start justify-between space-y-4 text-black-500">
                <div className="flex items-center justify-center mx-auto space-x-4 md:justify-end md:mx-0">
                  Get In Touch
                </div>
                <div className="flex items-center justify-center mx-auto space-x-4 md:justify-end md:mx-0">
                  <div className="h-8 group">
                    <a href="#">
                      <img src="facebook-black.svg" alt="" className="h-6" />
                    </a>
                  </div>
                  <div className="h-8 group">
                    <a href="#">
                      <img src="twitter-black.svg" alt="" className="h-6" />
                    </a>
                  </div>
                  <div className="h-8 group">
                    <a href="#">
                      <img src="vimeo-black.svg" alt="" className="h-6" />
                    </a>
                  </div>
                  <div className="h-8 group">
                    <a href="#">
                      <img src="youtube-black.svg" alt="" className="h-6" />
                    </a>
                  </div>
                </div>
              </div>
              <div className="flex flex-col items-center md:items-start justify-between space-y-4 text-black-500">
                <div>
                  <div>address</div>
                  <div>address</div>
                </div>
                <div>
                  <span>test@mail.com</span>
                </div>
                <div>
                  <span>1234567890</span>
                </div>
              </div>
            </div>
            <hr></hr>
            <div className="flex flex-col items-center space-y-6 md:flex-row md:space-y-0 md:justify-between py-4 mx-auto">
              <div className="flex flex-col items-center md:flex-row space-x-4">
                <div>Home</div>
                <div>Product</div>
                <div>Find A Dealer</div>
              </div>
              <div>
                <div>Copyright &copy; 2024</div>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
